services:
  web:
    build: ./web
    command: bash -c "rm -f tmp/pods/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  front:
    build: front/
    volumes:
      - ./front:/app:cache
    ports:
      - 8080:3000
    command: sh -c "yarn && yarn dev"

volumes:
  postgres-data:
